[workspace]
members = [
    "crates/bitang",
    "crates/bitang_utils",
]

[profile.dev.package."*"]
opt-level = 2
overflow-checks = false

[profile.dev.package.bitang]
opt-level = 0
overflow-checks = true

[profile.dev.package.egui]
opt-level = 0
overflow-checks = true

[patch.crates-io]
egui = { path = "crates/egui-patch/crates/egui" }

