[package]
name = "bitang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
blend = "0.6.1"
winit = "0.26.1"
image = "0.22"
num = "0.4.0"
cgmath = "0.18.0"
memoffset = "0.6.5"
tobj = "0.1.10"
bytemuck = "1.8.0"
thiserror = "1.0"
egui_vulkano = "0.8.0"
egui = "0.18.1"
vulkano = "0.29.0"
vulkano-shaders = "0.29.0"
vulkano-win = "0.29.0"
shaderc = "*"

[profile.dev.package."*"]
opt-level = 'z'
debug = false
debug-assertions = false
overflow-checks = false
