[workspace]
members = [
    "crates/bitang",
    "crates/bitang_utils",
]

[profile.dev.package."*"]
opt-level = 2
overflow-checks = false

[profile.dev.package.bitang]
opt-level = 0
overflow-checks = true
