[workspace]
members = [
    "crates/bitang",
    "crates/bitang_utils",
]

[profile.dev.package."*"]
opt-level = 2
overflow-checks = false

[profile.dev.package.bitang]
opt-level = 0
overflow-checks = true

[profile.dev.package.bitang_utils]
opt-level = 2
overflow-checks = false

[profile.dev.package.vulkano]
opt-level = 1

[profile.dev-nowarn]
inherits = "dev"

[profile.release-min]
inherits = "release"
strip = true
lto = true
panic = "abort"